// GENERATED by mariner -- do not edit
// Source: inst/brand/baylor/_brand.yml
// Regenerate: Rscript data-raw/build-tokens.R
// Edit the brand file, not this one.

#let qmd-background = rgb("#fefefe")
#let qmd-foreground = rgb("#222222")
#let qmd-baylor-green = rgb("#154734")
#let qmd-university-gold = rgb("#FFB81C")
#let qmd-gold-ink = rgb("#9b6e06")
#let qmd-gold-rule = rgb("#c28a01")
#let qmd-series-1-green = rgb("#017553")
#let qmd-series-2-gold = rgb("#c08802")
#let qmd-series-3-purple = rgb("#aa4499")
#let qmd-series-4-olive = rgb("#979731")
#let qmd-series-5-sky = rgb("#0178bc")
#let qmd-series-6-orange = rgb("#e8712a")
#let qmd-series-7-indigo = rgb("#493fa6")
#let qmd-series-8-rose = rgb("#cc6677")
#let qmd-seq-1 = rgb("#eaf7f1")
#let qmd-seq-2 = rgb("#c5d7ce")
#let qmd-seq-3 = rgb("#a0b9ad")
#let qmd-seq-4 = rgb("#7d9b8c")
#let qmd-seq-5 = rgb("#5b7e6d")
#let qmd-seq-6 = rgb("#396250")
#let qmd-seq-7 = rgb("#154734")
#let qmd-ord-1 = rgb("#a8b4ae")
#let qmd-ord-2 = rgb("#83988e")
#let qmd-ord-3 = rgb("#5f7c6e")
#let qmd-ord-4 = rgb("#3b6150")
#let qmd-ord-5 = rgb("#154734")
#let qmd-div-1 = rgb("#017553")
#let qmd-div-2 = rgb("#649c83")
#let qmd-div-3 = rgb("#a8c3b6")
#let qmd-div-4 = rgb("#e9ecea")
#let qmd-div-5 = rgb("#decaac")
#let qmd-div-6 = rgb("#cfaa6b")
#let qmd-div-7 = rgb("#c08802")
#let qmd-ink = rgb("#222222")
#let qmd-ink-secondary = rgb("#4a4f4b")
#let qmd-ink-muted = rgb("#6f7671")
#let qmd-rule-grid = rgb("#dfe3e0")
#let qmd-rule-axis = rgb("#c2c8c4")
#let qmd-primary = rgb("#154734")
#let qmd-secondary = rgb("#c28a01")
#let qmd-link = rgb("#154734")
#let qmd-accent-ink = rgb("#9a6e13")
#let qmd-accent-rule = rgb("#c28a01")
#let qmd-on-primary = rgb("#fefefe")
#let qmd-on-secondary = rgb("#222222")
#let qmd-series-1 = rgb("#017553")
#let qmd-series-2 = rgb("#c08802")
#let qmd-series-3 = rgb("#aa4499")
#let qmd-series-4 = rgb("#979731")
#let qmd-series-5 = rgb("#0178bc")
#let qmd-series-6 = rgb("#e8712a")
#let qmd-series-7 = rgb("#493fa6")
#let qmd-series-8 = rgb("#cc6677")

#let qmd-font-headings = "Atkinson Hyperlegible Next"
#let qmd-font-body = "Lora"
#let qmd-font-mono = "JetBrains Mono"

#let qmd-logo = "_extensions/mariner-baylor/logos/BU_BrandMark_Horz_Green.png"
#let qmd-logo-width = 1.4038in
#let qmd-logo-cover = "_extensions/mariner-baylor/logos/BU_BrandMark_Stacked_Green.png"
