# The generation chain.
#
#   inst/brand/<theme>/_brand.yml       <- hand-edited, the ONLY place a hex or a
#           |                              logo filename is typed
#           +-> _qmd-tokens.scss        $qmd-* SCSS variables
#           +-> _qmd-tokens-css.scss    :root { --qmd-*: ... } custom properties
#           +-> brand-preamble.tex      \definecolor + KOMA/hyperref/booktabs hooks
#           +-> _tokens.typ             Typst let-bindings
#           +-> _extension.yml          the Quarto format manifest
#
# Quarto's own `brand:` support reaches html, revealjs and typst but NOT LaTeX
# pdf, which is why the preamble is generated rather than hand-mirrored. The
# outputs are committed so the package works without a build step, and
# test-no-drift.R re-runs every generator into a temp dir and diffs, so a hex
# edited in _brand.yml without a rebuild fails R CMD check.
#
# Generated files carry the marker below. test-no-literal-hex.R uses it to tell
# "this file is allowed to contain hex codes" from "someone typed a colour here".
#
# Ported from QMDThemes and then changed in one substantive way: logo sizes are
# derived from the image files rather than written down. See R/logos.R.

GENERATED_MARKER <- "GENERATED by mariner -- do not edit"

generated_header <- function(theme, comment = "//") {
  paste0(
    comment, " ", GENERATED_MARKER, "\n",
    comment, " Source: inst/brand/", theme, "/_brand.yml\n",
    comment, " Regenerate: Rscript data-raw/build-tokens.R\n",
    comment, " Edit the brand file, not this one.\n"
  )
}

# Hand-written files reference tokens by these names, so the mapping from a
# _brand.yml key to a token name is fixed here rather than at each call site.
token_name <- function(key) gsub("[^a-z0-9]+", "-", tolower(key))

#' Generate the SCSS token file for a theme
#'
#' Emits one `$qmd-<token>` variable per colour in the theme's `_brand.yml`,
#' plus the font stacks, the slide geometry and the logo paths. Hand-written
#' SCSS references only these variables -- a literal hex in a stylesheet is a
#' test failure.
#'
#' @param theme One of [mariner_themes].
#' @return The file's contents, as a single string.
#' @noRd
build_scss_tokens <- function(theme = mariner_themes) {
  theme <- check_theme(theme)
  brand <- read_brand(theme)
  tok <- brand_tokens(brand)
  lines <- vapply(
    names(tok),
    function(k) sprintf("$qmd-%s: %s !default;", token_name(k), tok[[k]]),
    character(1)
  )
  roles <- brand_roles(brand)
  role_lines <- vapply(
    names(roles),
    function(k) sprintf("$qmd-%s: %s !default;", token_name(k), roles[[k]]),
    character(1)
  )
  ty <- brand$typography
  fonts <- c(
    sprintf('$qmd-font-headings: "%s", system-ui, sans-serif !default;', ty$headings$family),
    sprintf('$qmd-font-body: "%s", Georgia, serif !default;', ty$base$family),
    sprintf('$qmd-font-mono: "%s", ui-monospace, monospace !default;', ty$monospace),
    sprintf("$qmd-font-size-base: %s !default;", ty$base$size),
    sprintf("$qmd-line-height-base: %s !default;", ty$base$`line-height`),
    sprintf("$qmd-heading-weight: %s !default;", ty$headings$weight),
    # The extension's own directory, as the RENDERED DOCUMENT sees it.
    #
    # _qmd-typography.scss's @font-face rules need a url() to the bundled font
    # files, and Quarto resolves a theme file's url() against the output rather
    # than against the stylesheet. Where the output puts the compiled CSS
    # differs by format, so the two format partials build $qmd-font-path from
    # this and each adds its own prefix -- see qmd-html.scss and
    # qmd-revealjs.scss.
    sprintf('$qmd-ext-dir: "%s" !default;', mariner_ext_rel(theme))
  )
  # Slide geometry. NOT from _brand.yml -- a slide is the same size whatever the
  # theme -- but emitted here regardless, because _qmd-tokens.scss is the one
  # file a partial's defaults are allowed to reference (R/scss.R).
  slide <- slide_scss_tokens()
  slide_lines <- vapply(
    names(slide),
    function(k) sprintf("$qmd-%s: %s !default;", k, slide[[k]]),
    character(1)
  )
  logo <- logo_scss_tokens(theme)
  logo_lines <- vapply(
    names(logo),
    function(k) sprintf("$qmd-%s: %s !default;", k, logo[[k]]),
    character(1)
  )
  paste0(
    generated_header(theme), "\n",
    # Quarto refuses a theme file with no layer boundary outright -- it is an
    # error, not a default. Everything here is a variable, so it is all defaults.
    "/*-- scss:defaults --*/\n\n",
    "// Colours\n", paste(lines, collapse = "\n"), "\n\n",
    "// Semantic roles -- what the shared partials reference. See brand_roles().\n",
    paste(role_lines, collapse = "\n"), "\n\n",
    "// Typography\n", paste(fonts, collapse = "\n"), "\n\n",
    "// Slide geometry -- derived from MARINER_SLIDE in R/slides.R, not from the\n",
    "// brand file. The same numbers reach _extension.yml and mariner_fig_dims().\n",
    paste(slide_lines, collapse = "\n"), "\n\n",
    "// Brand marks. Filenames come from _brand.yml's logo: block; the cover\n",
    "// height is derived from the slide box and its width from the image's own\n",
    "// aspect ratio. See R/logos.R.\n",
    paste(logo_lines, collapse = "\n"), "\n"
  )
}

# The $qmd-logo-* block, as name/value pairs.
#
# The corner mark needs no width token: qmd-revealjs.scss sets its HEIGHT from
# $qmd-slide-logo-height and the browser derives the width, which is the same
# arithmetic this module does for the formats that cannot.
#
# The cover mark does need one, because a title slide places it rather than
# letting it sit in a corner, and a placed element wants both numbers.
logo_scss_tokens <- function(theme) {
  geom <- mariner_slide_geometry()
  cover_h <- geom$height * LOGO_HEIGHT$cover_frac
  c(
    "logo-corner"       = sprintf('"#{$qmd-ext-dir}/logos/%s"', mariner_logo_name(theme, "medium")),
    "logo-cover"        = sprintf('"#{$qmd-ext-dir}/logos/%s"', mariner_logo_name(theme, "large")),
    "logo-mark"         = sprintf('"#{$qmd-ext-dir}/logos/%s"', mariner_logo_name(theme, "small")),
    "logo-cover-height" = paste0(num_str(cover_h), "px"),
    "logo-cover-width"  = paste0(num_str(mariner_logo_width(cover_h, theme, "large")), "px")
  )
}

#' Generate the CSS custom-property file for a theme
#'
#' The same tokens as `build_scss_tokens()`, exposed on `:root` so a
#' hand-written span, an HTML table cell or a JS widget can reach a series
#' colour without the hex being typed again.
#'
#' @inheritParams build_scss_tokens
#' @return The file's contents, as a single string.
#' @noRd
build_css_tokens <- function(theme = mariner_themes) {
  theme <- check_theme(theme)
  brand <- read_brand(theme)
  all <- c(brand_tokens(brand), brand_roles(brand))
  lines <- vapply(
    names(all),
    function(k) sprintf("  --qmd-%s: %s;", token_name(k), all[[k]]),
    character(1)
  )
  paste0(
    generated_header(theme), "\n",
    # A :root block is a rule, and Quarto errors on a file with no layer marker.
    "/*-- scss:rules --*/\n\n",
    ":root {\n", paste(lines, collapse = "\n"), "\n}\n"
  )
}

# LaTeX command names cannot contain digits or hyphens, so tokens are mapped to
# letter-only names: series-1-green -> \qmdseriesonegreen.
tex_name <- function(key) {
  digits <- c("0" = "zero", "1" = "one", "2" = "two", "3" = "three", "4" = "four",
              "5" = "five", "6" = "six", "7" = "seven", "8" = "eight", "9" = "nine")
  out <- gsub("[^a-z0-9]", "", tolower(key))
  for (d in names(digits)) out <- gsub(d, digits[[d]], out, fixed = TRUE)
  paste0("qmd", out)
}

#' Generate the LaTeX preamble for a theme
#'
#' Quarto's `brand:` support does not reach LaTeX pdf, so the colours are
#' emitted as `\definecolor` and wired into KOMA's heading fonts, `hyperref`
#' link colours and `booktabs` rules here.
#'
#' @inheritParams build_scss_tokens
#' @return The file's contents, as a single string.
#' @noRd
build_pdf_preamble <- function(theme = mariner_themes) {
  theme <- check_theme(theme)
  brand <- read_brand(theme)
  all <- c(brand_tokens(brand), brand_roles(brand))
  defs <- vapply(
    names(all),
    function(k) sprintf("\\definecolor{%s}{HTML}{%s}", tex_name(k),
                        toupper(sub("^#", "", all[[k]]))),
    character(1)
  )
  primary <- tex_name("primary")
  link <- tex_name("link")
  ink <- tex_name("ink")

  ext <- mariner_ext_rel(theme)
  font_dir <- paste0(ext, "/fonts/")

  # The corner mark, sized from its own pixel dimensions.
  #
  # The old theme wrote a width per logo file, with a comment explaining that a
  # square mark and a wordmark could not share one. They share a HEIGHT instead,
  # and the width follows -- so this is the only placement number, and adding a
  # mark needs nothing here. See R/logos.R.
  logo_path <- paste0(ext, "/logos/", mariner_logo_name(theme, "medium"))
  logo_height <- LOGO_HEIGHT$pdf_corner_in
  logo_width <- num_str(mariner_logo_width(logo_height, theme, "medium"))

  paste0(
    generated_header(theme, "%"), "\n",
    "% Quarto loads xcolor itself. Passing the option rather than loading with it\n",
    "% avoids an option clash, and \"table\" brings in colortbl, which\n",
    "% \\arrayrulecolor below needs.\n",
    "\\PassOptionsToPackage{table}{xcolor}\n",
    "\\usepackage{xcolor}\n",
    "\\usepackage{booktabs}\n\n",
    "% The three faces, loaded from the files vendored in this extension.\n",
    "%\n",
    "% Here rather than in _extension.yml's mainfont/sansfont/monofont keys,\n",
    "% because pandoc LaTeX-ESCAPES the values of the matching *fontoptions keys:\n",
    "% `Path=_extensions/...` reaches the .tex as `Path=\\_extensions/...` and\n",
    "% xelatex fails with \"Missing \\begin{document}\" from inside \\setsansfont.\n",
    "% A header include is raw LaTeX and is passed through untouched.\n",
    "%\n",
    "% Loading by FILE, not by installed name: Atkinson Hyperlegible is not on any\n",
    "% machine by default, so naming it would silently fall back to a generic sans\n",
    "% -- and KOMA's scrartcl sets every heading through \\sffamily, which makes\n",
    "% the sans face the HEADING face. The static cuts are used rather than the\n",
    "% variable AtkinsonHyperlegibleNext[wght].ttf because XeTeX reaches only a\n",
    "% variable font's default instance, so bold and italic would be synthesised.\n",
    "%\n",
    "% Paths are relative to the .tex, which Quarto writes at the project root.\n",
    "\\usepackage{fontspec}\n",
    "\\setmainfont{Lora}[\n",
    "  Path=", font_dir, ",\n",
    "  Extension=.ttf,\n",
    "  UprightFont=*-Regular, BoldFont=*-Bold,\n",
    "  ItalicFont=*-Italic, BoldItalicFont=*-BoldItalic]\n",
    "\\setsansfont{AtkinsonHyperlegible}[\n",
    "  Path=", font_dir, ",\n",
    "  Extension=.ttf,\n",
    "  UprightFont=*-Regular, BoldFont=*-Bold,\n",
    "  ItalicFont=*-Italic, BoldItalicFont=*-BoldItalic]\n",
    "\\setmonofont{JetBrainsMono}[\n",
    "  Path=", font_dir, ",\n",
    "  Extension=.ttf,\n",
    "  Scale=MatchLowercase,\n",
    "  UprightFont=*-Regular, BoldFont=*-Bold,\n",
    "  ItalicFont=*-Italic, BoldItalicFont=*-BoldItalic]\n\n",
    paste(defs, collapse = "\n"), "\n\n",
    "% Body copy in the theme's near-black rather than pure black.\n",
    "\\AtBeginDocument{\\color{", ink, "}}\n\n",
    "% Headings in the primary colour. Quarto's default PDF class is KOMA's\n",
    "% scrartcl, where `disposition` is the font element every heading level\n",
    "% inherits from -- one line covers title, sections and subsections. The\n",
    "% guard means a document that overrides documentclass still compiles, just\n",
    "% without coloured headings.\n",
    "\\makeatletter\n",
    "\\@ifundefined{addtokomafont}{}{%\n",
    "  \\addtokomafont{disposition}{\\color{", primary, "}}%\n",
    "  \\addtokomafont{caption}{\\small}%\n",
    "  \\addtokomafont{captionlabel}{\\bfseries\\color{", primary, "}}%\n",
    "}\n",
    "\\makeatother\n\n",
    "% Deferred to \\AtBeginDocument because a header include lands in the\n",
    "% preamble BEFORE Quarto's template loads hyperref -- calling \\hypersetup\n",
    "% here directly fails with \"Undefined control sequence\".\n",
    "\\AtBeginDocument{%\n",
    "  \\hypersetup{colorlinks=true, linkcolor=", primary, ",\n",
    "    filecolor=", link, ", urlcolor=", link, ", citecolor=", link, "}%\n",
    "}\n\n",
    "% Rules in booktabs tables in the primary colour rather than black. The test\n",
    "% is \\ifcsname rather than \\@ifundefined on purpose: the body of\n",
    "% \\AtBeginDocument is tokenised where it is written, and \"@\" is not a letter\n",
    "% in the preamble, so a \\@... command inside it would be misparsed long\n",
    "% before \\makeatletter could take effect.\n",
    "\\AtBeginDocument{%\n",
    "  \\ifcsname arrayrulecolor\\endcsname\\arrayrulecolor{", primary, "}\\fi\n",
    "}\n\n",
    "% Definition cross-references, matching the .term / .defn classes in the\n",
    "% stylesheets so the same concept renders alike in every format.\n",
    "\\providecommand{\\texorpdfstring}[2]{#1}\n",
    "\\DeclareRobustCommand{\\defn}[1]{\\textcolor{", primary, "}{\\underline{\\textit{#1}}}}\n",
    "\\DeclareRobustCommand{\\linkeddefn}[2]{%\n",
    "  \\texorpdfstring{\\hypertarget{ref-#1}{\\hyperlink{def-#1}{\\defn{#2}}}}{\\defn{#2}}}\n",
    "\\DeclareRobustCommand{\\defanchor}[1]{\\texorpdfstring{\\hypertarget{def-#1}{}}{}}\n",
    "\\DeclareRobustCommand{\\backlink}[1]{%\n",
    "  \\texorpdfstring{\\hyperlink{ref-#1}{\\textcolor{", primary, "}{\\small$\\hookleftarrow$}}}{}}\n\n",
    "% Floats stay in the section that introduces them.\n",
    "%\n",
    "% fig-pos is 'htbp' (set in _extension.yml) so that an oversized figure can\n",
    "% move instead of running off the page -- but plain 'htbp' lets it move too\n",
    "% far: LaTeX defers a figure it cannot fit, and the deferred ones then pile\n",
    "% up on a later page AFTER the heading of the section that follows. Two\n",
    "% figures and the next subsection title end up in the wrong order.\n",
    "%\n",
    "% \\FloatBarrier flushes pending floats before each heading, which bounds the\n",
    "% drift to the section that owns them. The float fractions are relaxed at the\n",
    "% same time so a tall figure is accepted on a page with text rather than\n",
    "% being deferred in the first place -- barriers alone would just turn the\n",
    "% deferral into a half-empty page.\n",
    "%\n",
    "% Typst needs none of this: it has no float model, so its figures were always\n",
    "% in the right place.\n",
    "\\usepackage{placeins}\n",
    "\\makeatletter\n",
    "\\AtBeginDocument{%\n",
    "  \\@ifundefined{section}{}{%\n",
    "    \\let\\qmdorigsection\\section\n",
    "    \\renewcommand{\\section}{\\FloatBarrier\\qmdorigsection}}%\n",
    "  \\@ifundefined{subsection}{}{%\n",
    "    \\let\\qmdorigsubsection\\subsection\n",
    "    \\renewcommand{\\subsection}{\\FloatBarrier\\qmdorigsubsection}}%\n",
    "}\n",
    "\\makeatother\n",
    "\\renewcommand{\\topfraction}{0.9}\n",
    "\\renewcommand{\\bottomfraction}{0.8}\n",
    "\\renewcommand{\\textfraction}{0.07}\n",
    "\\renewcommand{\\floatpagefraction}{0.75}\n\n",
    "% The title block and the contents own the first page; the body starts on a\n",
    "% fresh one. Attached to \\tableofcontents rather than written as a \\clearpage\n",
    "% in the document, so it happens only when there IS a table of contents -- a\n",
    "% document with toc: false gets no stray blank page.\n",
    "%\n",
    "% Deferred to \\AtBeginDocument for the same reason \\hypersetup above is:\n",
    "% both KOMA and hyperref patch \\tableofcontents themselves at the start of\n",
    "% the document, so a plain \\renewcommand in the preamble is silently thrown\n",
    "% away and the break never happens.\n",
    "\\AtBeginDocument{%\n",
    "  \\let\\qmdorigtableofcontents\\tableofcontents\n",
    "  \\renewcommand{\\tableofcontents}{\\qmdorigtableofcontents\\clearpage}%\n",
    "}\n\n",
    "% The brand mark, in the bottom-right corner of the first page.\n",
    "%\n",
    "% eso-pic's starred form applies to the CURRENT page only, so this marks the\n",
    "% title page and leaves the body clean -- a logo repeated on every page of a\n",
    "% long report is noise. The origin is the bottom-left of the paper and \\put\n",
    "% positions the bottom-left of the BOX, so the vertical coordinate is just the\n",
    "% clearance from the paper edge; \\LenToUnit converts a LaTeX length into the\n",
    "% bare number \\put wants.\n",
    "%\n",
    "% Bottom rather than top because it cannot then collide with the title block,\n",
    "% which a top-right mark does on any document whose title runs long enough to\n",
    "% reach the margin.\n",
    "%\n",
    "% The width below is DERIVED: ", num_str(logo_height), "in tall, times the image's own aspect\n",
    "% ratio. Nothing here has to know which mark is in the medium slot.\n",
    "%\n",
    "% The path is relative to the .tex, which Quarto writes at the project root,\n",
    "% so it reaches the copy vendored inside the extension and needs nothing\n",
    "% copied into the project. \\includegraphics cannot read SVG, which is why the\n",
    "% bundled marks are PNG.\n",
    "\\usepackage{eso-pic}\n",
    "\\usepackage{graphicx}\n",
    "\\newlength{\\qmdlogowidth}\n",
    "\\setlength{\\qmdlogowidth}{", logo_width, "in}\n",
    "\\IfFileExists{", logo_path, "}{%\n",
    "  \\AddToShipoutPictureFG*{%\n",
    "    \\put(\\LenToUnit{\\dimexpr\\paperwidth-1in-\\qmdlogowidth\\relax},%\n",
    "         \\LenToUnit{0.4in}){%\n",
    "      \\includegraphics[width=\\qmdlogowidth]{", logo_path, "}}%\n",
    "  }%\n",
    "}{}\n"
  )
}

#' Generate the Typst token file for a theme
#'
#' @inheritParams build_scss_tokens
#' @return The file's contents, as a single string.
#' @noRd
build_typst_tokens <- function(theme = mariner_themes) {
  theme <- check_theme(theme)
  brand <- read_brand(theme)
  all <- c(brand_tokens(brand), brand_roles(brand))
  lines <- vapply(
    names(all),
    function(k) sprintf('#let qmd-%s = rgb("%s")', token_name(k), all[[k]]),
    character(1)
  )
  ty <- brand$typography
  ext <- mariner_ext_rel(theme)
  # Matches the LaTeX corner mark in build_pdf_preamble(), sized the same way,
  # so the two PDF engines put the same thing in the same place at the same
  # size.
  logo_height <- LOGO_HEIGHT$pdf_corner_in
  paste0(
    generated_header(theme, "//"), "\n",
    paste(lines, collapse = "\n"), "\n\n",
    sprintf('#let qmd-font-headings = "%s"\n', ty$headings$family),
    sprintf('#let qmd-font-body = "%s"\n', ty$base$family),
    sprintf('#let qmd-font-mono = "%s"\n', ty$monospace),
    # The corner mark. The path is relative to the .typ, which Quarto writes at
    # the project root.
    sprintf('\n#let qmd-logo = "%s/logos/%s"\n', ext, mariner_logo_name(theme, "medium")),
    sprintf('#let qmd-logo-width = %sin\n', num_str(mariner_logo_width(logo_height, theme, "medium"))),
    sprintf('#let qmd-logo-cover = "%s/logos/%s"\n', ext, mariner_logo_name(theme, "large"))
  )
}

#' Generate the HTML brand header for a theme
#'
#' The masthead the `html` format includes before the body.
#'
#' Generated rather than shipped as a static file because it names both the
#' extension directory and the logo file, and the alt text is the brand's own
#' name -- three things that already have a single source each. A static copy
#' would be a fourth place to update when any of them changes, and the failure
#' is silent: a wrong path renders as a broken-image icon, and stale alt text is
#' invisible to everyone except a screen-reader user.
#'
#' @inheritParams build_scss_tokens
#' @return The file's contents, as a single string.
#' @noRd
build_brand_header <- function(theme = mariner_themes) {
  theme <- check_theme(theme)
  brand <- read_brand(theme)
  # No comment marker: this file is included into the document body, and an HTML
  # comment would be served to the reader.
  sprintf(
    '<div class="qmd-brand-header">\n  <img src="%s/logos/%s" alt="%s" />\n</div>\n',
    mariner_ext_rel(theme),
    mariner_logo_name(theme, "medium"),
    brand_name(brand, "full")
  )
}

#' Generate the Quarto extension manifest for a theme
#'
#' The `_extension.yml` the theme contributes its four formats through.
#'
#' Generated rather than hand-written because reveal.js's `width:`/`height:` are
#' read by Quarto before any stylesheet exists, so they cannot come from SCSS;
#' deriving them from `mariner_slide_geometry()` here is what keeps the slide
#' box, the CSS caps and the knitr figure defaults from being three separate
#' opinions.
#'
#' @inheritParams build_scss_tokens
#' @return The file's contents, as a single string.
#' @noRd
build_extension_yml <- function(theme = mariner_themes) {
  theme <- check_theme(theme)
  ext <- mariner_ext_rel(theme)

  geom <- mariner_slide_geometry()
  scss <- function(format) {
    paste0("        - ", mariner_scss_files(theme, format, absolute = FALSE), collapse = "\n")
  }

  paste0(
    "# ", GENERATED_MARKER, "\n",
    "# Source: R/generate.R (build_extension_yml), R/scss.R, R/slides.R, R/logos.R\n",
    "# Regenerate: Rscript data-raw/build-tokens.R\n",
    "# Edit the generator, not this file.\n\n",
    "title: Mariner ", tools::toTitleCase(theme), "\n",
    "author: Thomas Reinke\n",
    "version: 0.2.0\n",
    'quarto-required: ">=1.4.0"\n',
    "contributes:\n",
    "  formats:\n",
    "    html:\n",
    "      theme:\n",
    "        - cosmo\n", scss("html"), "\n",
    "      highlight-style: a11y\n",
    "      toc: true\n",
    "      toc-depth: 3\n",
    "      code-copy: hover\n",
    "      embed-resources: true\n",
    "      include-before-body:\n",
    "        - brand-header.html\n",
    "      include-after-body:\n",
    "        - zoom.js\n",
    "      execute:\n",
    "        echo: false\n",
    "        warning: false\n",
    "        message: false\n",
    "      knitr:\n",
    "        opts_chunk:\n",
    "          fig-format: svg\n",
    "          dpi: 300\n",
    '          comment: "#>"\n',
    "          collapse: true\n\n",

    "    revealjs:\n",
    "      # The horizontal wordmark. Its HEIGHT is set by qmd-revealjs.scss from\n",
    "      # $qmd-slide-logo-height and the browser derives the width, so unlike\n",
    "      # the pdf and typst corner marks this one needs no computed width.\n",
    "      logo: ", ext, "/logos/", mariner_logo_name(theme, "medium"), "\n",
    "      theme:\n",
    "        - default\n", scss("revealjs"), "\n",
    "      # The slide box, in reveal's own coordinate space. Quarto reads these\n",
    "      # before any stylesheet exists, so they cannot come from SCSS -- they\n",
    "      # and the $qmd-slide-* tokens are generated from the same constants in\n",
    "      # R/slides.R instead, which is what stops the caps in the stylesheet\n",
    "      # from being measured against a box the deck no longer has.\n",
    "      width: ", num_str(geom$width), "\n",
    "      height: ", num_str(geom$height), "\n",
    "      # The share of the window reveal will not scale the slide into. The\n",
    "      # slide counter is moved into that gutter by qmd-revealjs.scss, so this\n",
    "      # has a floor: below ", num_str(round(geom$margin_min, 3)), " the counter climbs out of the top of\n",
    "      # the window. mariner_slide_geometry() computes it, and the test suite\n",
    "      # asserts this value clears it.\n",
    "      margin: ", num_str(geom$margin), "\n",
    "      slide-number: c/t\n",
    "      auto-animate: true\n",
    "      embed-resources: true\n",
    "      highlight-style: a11y\n",
    "      center: false\n",
    "      transition: fade\n",
    "      execute:\n",
    "        echo: false\n",
    "        warning: false\n",
    "        message: false\n",
    "      knitr:\n",
    "        opts_chunk:\n",
    "          fig-format: svg\n",
    "          # The slide, less the heading bar -- mariner_fig_dims(\"revealjs\"),\n",
    "          # at 100px to the inch. A figure on a slide of its own therefore\n",
    "          # binds on width and fills the slide.\n",
    "          fig-width: ", num_str(geom$fig_width_in), "\n",
    "          fig-height: ", num_str(geom$fig_height_in), "\n",
    "          dpi: 300\n",
    '          comment: "#>"\n',
    "          collapse: true\n\n",

    "    pdf:\n",
    "      pdf-engine: xelatex\n",
    "      # Quarto defaults fig-pos to 'H', which with the float package means \"set it\n",
    "      # exactly here and never move it\" -- so a figure that does not fit in the\n",
    "      # space left on the page runs off the bottom instead of floating, and the\n",
    "      # footer page number prints on top of it. Restoring normal LaTeX float\n",
    "      # placement keeps figures near their text but lets one move when it cannot\n",
    "      # fit.\n",
    "      fig-pos: 'htbp'\n",
    "      # Fonts are set in brand-preamble.tex, NOT here. Pandoc LaTeX-escapes the\n",
    "      # values of mainfontoptions/sansfontoptions/monofontoptions, so a\n",
    "      # Path=_extensions/... came out as Path=\\_extensions/... and xelatex died\n",
    "      # with \"Missing \\begin{document}\" inside \\setsansfont. The preamble is\n",
    "      # raw LaTeX and is not escaped, so the paths survive intact there.\n",
    "      fontsize: 11pt\n",
    "      geometry:\n",
    "        - top=0.75in\n",
    "        - bottom=0.75in\n",
    "        - left=1in\n",
    "        - right=1in\n",
    "        - footskip=0.3in\n",
    "      include-in-header:\n",
    "        - file: brand-preamble.tex\n",
    "        - file: _macros.tex\n",
    "        - file: defn.tex\n",
    "      highlight-style: a11y\n",
    "      toc: true\n",
    "      toc-depth: 3\n",
    "      number-sections: true\n",
    "      execute:\n",
    "        echo: false\n",
    "        warning: false\n",
    "        message: false\n",
    "      knitr:\n",
    "        opts_chunk:\n",
    '          dev: "cairo_pdf"\n',
    "          fig-format: pdf\n",
    "          dpi: 300\n",
    '          comment: "#>"\n',
    "          collapse: true\n\n",

    "    typst:\n",
    "      # Atkinson Hyperlegible Next is bundled, not installed, so Typst cannot\n",
    "      # find it by name -- it warned \"unknown font family\" and silently fell\n",
    "      # back on every heading. This points Typst at the vendored copies.\n",
    "      font-paths:\n",
    "        - ", ext, "/fonts\n",
    '      mainfont: "Lora"\n',
    '      monofont: "JetBrains Mono"\n',
    "      fontsize: 11pt\n",
    "      margin:\n",
    "        top: 0.75in\n",
    "        bottom: 0.75in\n",
    "        left: 1in\n",
    "        right: 1in\n",
    "      # typst-header.typ must be a HEADER include, not a before-body one: Quarto\n",
    "      # emits $typst-show.typ$ (which wraps everything in article(), and\n",
    "      # article() is what renders the outline and the title block) BEFORE\n",
    "      # $include-before$, so a show rule placed in before-body is scoped inside\n",
    "      # the body and never matches either of them.\n",
    "      # _tokens.typ is a HEADER include so its $qmd-* bindings exist before\n",
    "      # typst-header.typ runs. Those bindings are at the outermost scope, so\n",
    "      # typst-rules.typ still sees them from inside the body.\n",
    "      include-in-header:\n",
    "        - file: _tokens.typ\n",
    "        - file: typst-header.typ\n",
    "      include-before-body:\n",
    "        - file: typst-rules.typ\n",
    "      highlight-style: a11y\n",
    "      toc: true\n",
    "      toc-depth: 3\n",
    "      number-sections: true\n",
    "      execute:\n",
    "        echo: false\n",
    "        warning: false\n",
    "        message: false\n",
    "      knitr:\n",
    "        opts_chunk:\n",
    "          fig-format: svg\n",
    "          dpi: 300\n",
    '          comment: "#>"\n',
    "          collapse: true\n"
  )
}

# Where each generated file lands. One list so the build script and the drift
# test cannot disagree about it.
generated_files <- function(theme) {
  dir <- file.path("inst", "quarto", "_extensions", mariner_ext_name(theme))
  list(
    # The `qmd-` prefix keeps these off Bootstrap's toes on the Sass load path;
    # see the note in R/scss.R.
    `_qmd-tokens.scss`     = list(path = file.path(dir, "_qmd-tokens.scss"),     fn = build_scss_tokens),
    `_qmd-tokens-css.scss` = list(path = file.path(dir, "_qmd-tokens-css.scss"), fn = build_css_tokens),
    `brand-preamble.tex`   = list(path = file.path(dir, "brand-preamble.tex"),   fn = build_pdf_preamble),
    `_tokens.typ`          = list(path = file.path(dir, "_tokens.typ"),          fn = build_typst_tokens),
    `brand-header.html`    = list(path = file.path(dir, "brand-header.html"),    fn = build_brand_header),
    `_extension.yml`       = list(path = file.path(dir, "_extension.yml"),       fn = build_extension_yml)
  )
}

#' Synchronize extension assets and shared partials
#'
#' Copies the shared SCSS partials, bundled fonts, logos, TeX includes and Typst
#' rules into the theme's extension directory under
#' `inst/quarto/_extensions/`, so the extension is fully self-contained once
#' scaffolded into a project by `mariner_setup_project()`.
#'
#' @param root Package source root directory.
#' @param quiet Suppress the summary message.
#' @return Invisibly returns the copied file paths.
#' @noRd
sync_extension_assets <- function(root = ".", quiet = FALSE) {
  copied <- character()

  scss_files <- list.files(file.path(root, "inst", "scss"), pattern = "\\.scss$", full.names = TRUE)
  font_files <- list.files(file.path(root, "inst", "assets", "fonts"), pattern = "\\.(ttf|txt)$", full.names = TRUE)
  tex_files  <- list.files(file.path(root, "inst", "tex"), pattern = "\\.tex$", full.names = TRUE)
  typ_files  <- list.files(file.path(root, "inst", "typst"), pattern = "\\.typ$", full.names = TRUE)
  # zoom.js only. brand-header.html is GENERATED into the same directory by
  # build_brand_header(), because it names the extension and the logo file.
  js_files   <- list.files(file.path(root, "inst", "html"), pattern = "\\.js$", full.names = TRUE)
  # Every mark, not just the ones wired up today. They are ~35 KB together, and
  # a template that reaches for the stacked lockup should not need a rebuild.
  logo_files <- list.files(file.path(root, "inst", "assets", "logos"), pattern = "\\.(png|svg)$", full.names = TRUE)

  copy_into <- function(files, dir) {
    dir.create(dir, recursive = TRUE, showWarnings = FALSE)
    for (f in files) {
      dest <- file.path(dir, basename(f))
      file.copy(f, dest, overwrite = TRUE)
      copied <<- c(copied, dest)
    }
  }

  for (theme in mariner_themes) {
    ext_dir <- file.path(root, "inst", "quarto", "_extensions", mariner_ext_name(theme))
    copy_into(c(typ_files, scss_files, tex_files, js_files), ext_dir)
    copy_into(font_files, file.path(ext_dir, "fonts"))
    copy_into(logo_files, file.path(ext_dir, "logos"))
  }

  if (!quiet) {
    cli::cli_alert_success("synchronized extension assets for {paste(mariner_themes, collapse = ', ')}")
  }
  invisible(copied)
}

#' Regenerate every derived artefact
#'
#' Writes the SCSS, CSS, LaTeX, Typst and extension-manifest files for the
#' theme, then copies the shared partials, fonts and logos into the extension
#' directory. Called by `data-raw/build-tokens.R`;
#' `tests/testthat/test-no-drift.R` calls it into a temporary directory and
#' diffs against what is committed.
#'
#' @param root Package source root.
#' @param quiet Suppress the per-file message.
#' @return The paths written, invisibly.
#' @noRd
build_tokens <- function(root = ".", quiet = FALSE) {
  written <- character()
  for (theme in mariner_themes) {
    for (spec in generated_files(theme)) {
      path <- file.path(root, spec$path)
      dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
      # cat(), not writeLines(): the generators already end their output with a
      # newline, and writeLines() would add a second one. The drift test compares
      # bytes, so that stray byte is the difference between pass and fail.
      cat(spec$fn(theme), file = path)
      written <- c(written, path)
      if (!quiet) cli::cli_alert_success("wrote {.file {spec$path}}")
    }
  }
  sync_extension_assets(root = root, quiet = quiet)
  invisible(written)
}
