# The generation chain.
#
#   inst/brand/<theme>/_brand.yml       <- hand-edited, the ONLY place a hex or a
#           |                              logo filename is typed
#           +-> brand-preamble.tex      \definecolor + KOMA/hyperref/booktabs hooks
#           +-> _extension.yml          the Quarto format manifest
#
# Quarto's own `brand:` support does not reach LaTeX pdf, which is why the
# preamble is generated rather than hand-mirrored. The outputs are committed to
# inst/generated/<theme>/ so the package works without a build step, and
# test-no-drift.R re-runs every generator into a temp dir and diffs, so a hex
# edited in _brand.yml without a rebuild fails R CMD check.
#
# They are the ONLY build outputs under inst/. The extension directory Quarto
# reads is assembled on demand from these plus the shared TeX includes, fonts
# and logos -- see R/extension.R.
#
# Generated files carry the marker below, which is what lets the drift test tell
# "this file is allowed to contain hex codes" from "someone typed a colour here".
#
# Ported from QMDThemes and then changed in two substantive ways: logo sizes are
# derived from the image files rather than written down (see R/logos.R), and the
# html, revealjs and typst formats are gone. mariner targets pdf reports; the
# stylesheets and Typst bindings that served the other three were deleted rather
# than carried unused, and are recoverable from git history if a second format
# is ever wanted.

GENERATED_MARKER <- "GENERATED by mariner -- do not edit"

generated_header <- function(theme, comment = "//") {
  paste0(
    comment, " ", GENERATED_MARKER, "\n",
    comment, " Source: inst/brand/", theme, "/_brand.yml\n",
    comment, " Regenerate: Rscript data-raw/build-tokens.R\n",
    comment, " Edit the brand file, not this one.\n"
  )
}

# LaTeX command names cannot contain digits or hyphens, so tokens are mapped to
# letter-only names: series-1-green -> \qmdseriesonegreen.
tex_name <- function(key) {
  digits <- c("0" = "zero", "1" = "one", "2" = "two", "3" = "three", "4" = "four",
              "5" = "five", "6" = "six", "7" = "seven", "8" = "eight", "9" = "nine")
  out <- gsub("[^a-z0-9]", "", tolower(key))
  for (d in names(digits)) out <- gsub(d, digits[[d]], out, fixed = TRUE)
  paste0("qmd", out)
}

#' Generate the LaTeX preamble for a theme
#'
#' Quarto's `brand:` support does not reach LaTeX pdf, so the colours are
#' emitted as `\definecolor` and wired into KOMA's heading fonts, `hyperref`
#' link colours and `booktabs` rules here.
#'
#' @param theme One of [mariner_themes].
#' @return The file's contents, as a single string.
#' @noRd
build_pdf_preamble <- function(theme = mariner_themes) {
  theme <- check_theme(theme)
  brand <- read_brand(theme)
  all <- c(brand_tokens(brand), brand_roles(brand))
  defs <- vapply(
    names(all),
    function(k) sprintf("\\definecolor{%s}{HTML}{%s}", tex_name(k),
                        toupper(sub("^#", "", all[[k]]))),
    character(1)
  )
  primary <- tex_name("primary")
  link <- tex_name("link")
  ink <- tex_name("ink")

  ext <- mariner_ext_rel(theme)
  font_dir <- paste0(ext, "/fonts/")

  # The corner mark, sized from its own pixel dimensions.
  #
  # The old theme wrote a width per logo file, with a comment explaining that a
  # square mark and a wordmark could not share one. They share a HEIGHT instead,
  # and the width follows -- so this is the only placement number, and adding a
  # mark needs nothing here. See R/logos.R.
  logo_path <- paste0(ext, "/logos/", mariner_logo_name(theme, "medium"))
  logo_height <- LOGO_HEIGHT$pdf_corner_in
  logo_width <- num_str(mariner_logo_width(logo_height, theme, "medium"))

  paste0(
    generated_header(theme, "%"), "\n",
    "% Quarto loads xcolor itself. Passing the option rather than loading with it\n",
    "% avoids an option clash, and \"table\" brings in colortbl, which\n",
    "% \\arrayrulecolor below needs.\n",
    "\\PassOptionsToPackage{table}{xcolor}\n",
    "\\usepackage{xcolor}\n",
    "\\usepackage{booktabs}\n\n",
    "% The three faces, loaded from the files vendored in this extension.\n",
    "%\n",
    "% Here rather than in _extension.yml's mainfont/sansfont/monofont keys,\n",
    "% because pandoc LaTeX-ESCAPES the values of the matching *fontoptions keys:\n",
    "% `Path=_extensions/...` reaches the .tex as `Path=\\_extensions/...` and\n",
    "% xelatex fails with \"Missing \\begin{document}\" from inside \\setsansfont.\n",
    "% A header include is raw LaTeX and is passed through untouched.\n",
    "%\n",
    "% Loading by FILE, not by installed name: Atkinson Hyperlegible is not on any\n",
    "% machine by default, so naming it would silently fall back to a generic sans\n",
    "% -- and KOMA's scrartcl sets every heading through \\sffamily, which makes\n",
    "% the sans face the HEADING face. The static cuts are used rather than the\n",
    "% variable AtkinsonHyperlegibleNext[wght].ttf because XeTeX reaches only a\n",
    "% variable font's default instance, so bold and italic would be synthesised.\n",
    "%\n",
    "% Paths are relative to the .tex, which Quarto writes at the project root.\n",
    "\\usepackage{fontspec}\n",
    "\\setmainfont{Lora}[\n",
    "  Path=", font_dir, ",\n",
    "  Extension=.ttf,\n",
    "  UprightFont=*-Regular, BoldFont=*-Bold,\n",
    "  ItalicFont=*-Italic, BoldItalicFont=*-BoldItalic]\n",
    "\\setsansfont{AtkinsonHyperlegible}[\n",
    "  Path=", font_dir, ",\n",
    "  Extension=.ttf,\n",
    "  UprightFont=*-Regular, BoldFont=*-Bold,\n",
    "  ItalicFont=*-Italic, BoldItalicFont=*-BoldItalic]\n",
    "\\setmonofont{JetBrainsMono}[\n",
    "  Path=", font_dir, ",\n",
    "  Extension=.ttf,\n",
    "  Scale=MatchLowercase,\n",
    "  UprightFont=*-Regular, BoldFont=*-Bold,\n",
    "  ItalicFont=*-Italic, BoldItalicFont=*-BoldItalic]\n\n",
    paste(defs, collapse = "\n"), "\n\n",
    "% Body copy in the theme's near-black rather than pure black.\n",
    "\\AtBeginDocument{\\color{", ink, "}}\n\n",
    "% Headings in the primary colour. Quarto's default PDF class is KOMA's\n",
    "% scrartcl, where `disposition` is the font element every heading level\n",
    "% inherits from -- one line covers title, sections and subsections. The\n",
    "% guard means a document that overrides documentclass still compiles, just\n",
    "% without coloured headings.\n",
    "\\makeatletter\n",
    "\\@ifundefined{addtokomafont}{}{%\n",
    "  \\addtokomafont{disposition}{\\color{", primary, "}}%\n",
    "  \\addtokomafont{caption}{\\small}%\n",
    "  \\addtokomafont{captionlabel}{\\bfseries\\color{", primary, "}}%\n",
    "}\n",
    "\\makeatother\n\n",
    "% Deferred to \\AtBeginDocument because a header include lands in the\n",
    "% preamble BEFORE Quarto's template loads hyperref -- calling \\hypersetup\n",
    "% here directly fails with \"Undefined control sequence\".\n",
    "\\AtBeginDocument{%\n",
    "  \\hypersetup{colorlinks=true, linkcolor=", primary, ",\n",
    "    filecolor=", link, ", urlcolor=", link, ", citecolor=", link, "}%\n",
    "}\n\n",
    "% Rules in booktabs tables in the primary colour rather than black. The test\n",
    "% is \\ifcsname rather than \\@ifundefined on purpose: the body of\n",
    "% \\AtBeginDocument is tokenised where it is written, and \"@\" is not a letter\n",
    "% in the preamble, so a \\@... command inside it would be misparsed long\n",
    "% before \\makeatletter could take effect.\n",
    "\\AtBeginDocument{%\n",
    "  \\ifcsname arrayrulecolor\\endcsname\\arrayrulecolor{", primary, "}\\fi\n",
    "}\n\n",
    "% Definition cross-references, for the \\linkeddefn / \\defanchor pair in\n",
    "% defn.tex.\n",
    "\\providecommand{\\texorpdfstring}[2]{#1}\n",
    "\\DeclareRobustCommand{\\defn}[1]{\\textcolor{", primary, "}{\\underline{\\textit{#1}}}}\n",
    "\\DeclareRobustCommand{\\linkeddefn}[2]{%\n",
    "  \\texorpdfstring{\\hypertarget{ref-#1}{\\hyperlink{def-#1}{\\defn{#2}}}}{\\defn{#2}}}\n",
    "\\DeclareRobustCommand{\\defanchor}[1]{\\texorpdfstring{\\hypertarget{def-#1}{}}{}}\n",
    "\\DeclareRobustCommand{\\backlink}[1]{%\n",
    "  \\texorpdfstring{\\hyperlink{ref-#1}{\\textcolor{", primary, "}{\\small$\\hookleftarrow$}}}{}}\n\n",
    "% Floats stay in the section that introduces them.\n",
    "%\n",
    "% fig-pos is 'htbp' (set in _extension.yml) so that an oversized figure can\n",
    "% move instead of running off the page -- but plain 'htbp' lets it move too\n",
    "% far: LaTeX defers a figure it cannot fit, and the deferred ones then pile\n",
    "% up on a later page AFTER the heading of the section that follows. Two\n",
    "% figures and the next subsection title end up in the wrong order.\n",
    "%\n",
    "% \\FloatBarrier flushes pending floats before each heading, which bounds the\n",
    "% drift to the section that owns them. The float fractions are relaxed at the\n",
    "% same time so a tall figure is accepted on a page with text rather than\n",
    "% being deferred in the first place -- barriers alone would just turn the\n",
    "% deferral into a half-empty page.\n",
    "\\usepackage{placeins}\n",
    "\\makeatletter\n",
    "\\AtBeginDocument{%\n",
    "  \\@ifundefined{section}{}{%\n",
    "    \\let\\qmdorigsection\\section\n",
    "    \\renewcommand{\\section}{\\FloatBarrier\\qmdorigsection}}%\n",
    "  \\@ifundefined{subsection}{}{%\n",
    "    \\let\\qmdorigsubsection\\subsection\n",
    "    \\renewcommand{\\subsection}{\\FloatBarrier\\qmdorigsubsection}}%\n",
    "}\n",
    "\\makeatother\n",
    "\\renewcommand{\\topfraction}{0.9}\n",
    "\\renewcommand{\\bottomfraction}{0.8}\n",
    "\\renewcommand{\\textfraction}{0.07}\n",
    "\\renewcommand{\\floatpagefraction}{0.75}\n\n",
    "% The title block and the contents own the first page; the body starts on a\n",
    "% fresh one. Attached to \\tableofcontents rather than written as a \\clearpage\n",
    "% in the document, so it happens only when there IS a table of contents -- a\n",
    "% document with toc: false gets no stray blank page.\n",
    "%\n",
    "% Deferred to \\AtBeginDocument for the same reason \\hypersetup above is:\n",
    "% both KOMA and hyperref patch \\tableofcontents themselves at the start of\n",
    "% the document, so a plain \\renewcommand in the preamble is silently thrown\n",
    "% away and the break never happens.\n",
    "\\AtBeginDocument{%\n",
    "  \\let\\qmdorigtableofcontents\\tableofcontents\n",
    "  \\renewcommand{\\tableofcontents}{\\qmdorigtableofcontents\\clearpage}%\n",
    "}\n\n",
    "% The brand mark, in the bottom-right corner of the first page.\n",
    "%\n",
    "% eso-pic's starred form applies to the CURRENT page only, so this marks the\n",
    "% title page and leaves the body clean -- a logo repeated on every page of a\n",
    "% long report is noise. The origin is the bottom-left of the paper and \\put\n",
    "% positions the bottom-left of the BOX, so the vertical coordinate is just the\n",
    "% clearance from the paper edge; \\LenToUnit converts a LaTeX length into the\n",
    "% bare number \\put wants.\n",
    "%\n",
    "% Bottom rather than top because it cannot then collide with the title block,\n",
    "% which a top-right mark does on any document whose title runs long enough to\n",
    "% reach the margin.\n",
    "%\n",
    "% The width below is DERIVED: ", num_str(logo_height), "in tall, times the image's own aspect\n",
    "% ratio. Nothing here has to know which mark is in the medium slot.\n",
    "%\n",
    "% The path is relative to the .tex, which Quarto writes at the project root,\n",
    "% so it reaches the copy vendored inside the extension and needs nothing\n",
    "% copied into the project. \\includegraphics cannot read SVG, which is why the\n",
    "% bundled marks are PNG.\n",
    "\\usepackage{eso-pic}\n",
    "\\usepackage{graphicx}\n",
    "\\newlength{\\qmdlogowidth}\n",
    "\\setlength{\\qmdlogowidth}{", logo_width, "in}\n",
    "\\IfFileExists{", logo_path, "}{%\n",
    "  \\AddToShipoutPictureFG*{%\n",
    "    \\put(\\LenToUnit{\\dimexpr\\paperwidth-1in-\\qmdlogowidth\\relax},%\n",
    "         \\LenToUnit{0.4in}){%\n",
    "      \\includegraphics[width=\\qmdlogowidth]{", logo_path, "}}%\n",
    "  }%\n",
    "}{}\n"
  )
}
#' Generate the Quarto extension manifest for a theme
#'
#' The `_extension.yml` the theme contributes its `pdf` format through.
#'
#' Generated rather than hand-written because it names the LaTeX includes and
#' the engine settings the preamble assumes, and because the version has to
#' match the package's. Each of those has a single source elsewhere, and none of
#' them fails loudly when a hand-written copy falls behind.
#'
#' @param theme One of [mariner_themes].
#' @return The file's contents, as a single string.
#' @noRd
build_extension_yml <- function(theme = mariner_themes) {
  theme <- check_theme(theme)

  paste0(
    "# ", GENERATED_MARKER, "\n",
    "# Source: R/generate.R (build_extension_yml), R/logos.R\n",
    "# Regenerate: Rscript data-raw/build-tokens.R\n",
    "# Edit the generator, not this file.\n\n",
    "title: Mariner ", tools::toTitleCase(theme), "\n",
    "author: Thomas Reinke\n",
    "version: 0.2.0\n",
    'quarto-required: ">=1.4.0"\n',
    "contributes:\n",
    "  formats:\n",
    "    pdf:\n",
    "      pdf-engine: xelatex\n",
    "      # Quarto defaults fig-pos to 'H', which with the float package means \"set it\n",
    "      # exactly here and never move it\" -- so a figure that does not fit in the\n",
    "      # space left on the page runs off the bottom instead of floating, and the\n",
    "      # footer page number prints on top of it. Restoring normal LaTeX float\n",
    "      # placement keeps figures near their text but lets one move when it cannot\n",
    "      # fit.\n",
    "      fig-pos: 'htbp'\n",
    "      # Fonts are set in brand-preamble.tex, NOT here. Pandoc LaTeX-escapes the\n",
    "      # values of mainfontoptions/sansfontoptions/monofontoptions, so a\n",
    "      # Path=_extensions/... came out as Path=\\_extensions/... and xelatex died\n",
    "      # with \"Missing \\begin{document}\" inside \\setsansfont. The preamble is\n",
    "      # raw LaTeX and is not escaped, so the paths survive intact there.\n",
    "      fontsize: 11pt\n",
    "      geometry:\n",
    "        - top=0.75in\n",
    "        - bottom=0.75in\n",
    "        - left=1in\n",
    "        - right=1in\n",
    "        - footskip=0.3in\n",
    "      include-in-header:\n",
    "        - file: brand-preamble.tex\n",
    "        - file: _macros.tex\n",
    "        - file: defn.tex\n",
    "      highlight-style: a11y\n",
    "      toc: true\n",
    "      toc-depth: 3\n",
    "      number-sections: true\n",
    "      execute:\n",
    "        echo: false\n",
    "        warning: false\n",
    "        message: false\n",
    "      knitr:\n",
    "        opts_chunk:\n",
    '          dev: "cairo_pdf"\n',
    "          fig-format: pdf\n",
    "          dpi: 300\n",
    '          comment: "#>"\n',
    "          collapse: true\n"
  )
}

generated_files <- function(theme) {
  dir <- file.path("inst", "generated", theme)
  list(
    `brand-preamble.tex` = list(path = file.path(dir, "brand-preamble.tex"), fn = build_pdf_preamble),
    `_extension.yml`     = list(path = file.path(dir, "_extension.yml"),     fn = build_extension_yml)
  )
}

#' Regenerate every derived artefact
#'
#' Writes the LaTeX preamble and the extension manifest
#' for each theme into `inst/generated/<theme>/`. Called by
#' `data-raw/build-tokens.R`; `tests/testthat/test-no-drift.R` calls it into a
#' temporary directory and diffs against what is committed.
#'
#' It does NOT assemble an extension directory. The shared partials, fonts and
#' logos are copied into one only when a project or a render scratch directory
#' asks for it -- see `mariner_build_extension()` in R/extension.R.
#'
#' @param root Package source root.
#' @param quiet Suppress the per-file message.
#' @return The paths written, invisibly.
#' @noRd
build_tokens <- function(root = ".", quiet = FALSE) {
  written <- character()
  for (theme in mariner_themes) {
    for (spec in generated_files(theme)) {
      path <- file.path(root, spec$path)
      dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
      # cat(), not writeLines(): the generators already end their output with a
      # newline, and writeLines() would add a second one. The drift test compares
      # bytes, so that stray byte is the difference between pass and fail.
      cat(spec$fn(theme), file = path)
      written <- c(written, path)
      if (!quiet) cli::cli_alert_success("wrote {.file {spec$path}}")
    }
  }
  invisible(written)
}
